### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by TBomberman** [DaoSeeder/interface#39]
![image](https://user-images.githubusercontent.com/9112273/224838255-a35c1b06-eb52-4aa3-9de2-60d1fa45e232.png)

1. The Expiration block is 0, but the current block is already 17. That means that the stage should be in Voting and evaluation stage but it says "In ProgressVoting and evaluation".
2. The commit Funds button should be disabled or removed after it expires.

**Comment by UsamaSaleem14** [comment]
Since the stage was not marked as complete that is why it is still showing In Progress.
